// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
  }
}

export {}
