// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppImage: typeof import('./src/components/AppImage.vue')['default']
    AppPage: typeof import('./src/components/AppPage/index.vue')['default']
    AppPicker: typeof import('./src/components/AppPicker/index.vue')['default']
    Auth: typeof import('./src/components/AppPage/Auth.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    Preload: typeof import('./src/components/AppPage/Preload.vue')['default']
    QRcode: typeof import('./src/components/QRcode/index.vue')['default']
    Reader: typeof import('./src/components/Reader.vue')['default']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
  }
}
